### ISSUE TITLE
Change Key Bind

### ISSUE THREAD

**Issue by brynnie1** [propstg/ambulance-mission#12]
So I am wanting to change the keybind from "E" to "Home" but when I change it in the config it works however still shows the message top left " Press E to start mission" where do I change that to reflect the correct Keybind

**Comment by propstg** [comment]
Hey,

You would need to change `Config.ActivationKeyText` from `"INPUT_CONTEXT"` to whatever the appropriate "Name" is for value you used for `Config.ActivationKey`. You should be able to find the name on the [controls page](https://docs.fivem.net/game-references/controls/) in the FiveM docs.

Let me know if you have any issues. Thanks!
