### ISSUE TITLE
Vehicle model Hash

### ISSUE THREAD

**Issue by Draenaii** [propstg/ambulance-mission#14]
I really like the concept of this script, but it has some flaws. I cannot get the hash key of an addon ambulance. Could you make it so that it looks to the modelname or something else for which I don't need the hash key. Hope you'll add this. Thanks!

**Comment by propstg** [comment]
Hey, thanks for the suggestion. I'll take a stab at it, when I get a chance.

Feel free to create issues for any other flaws, in the meantime. :)

Thanks!

**Comment by propstg** [comment]
Hey, I merged a change that should let you use add on ambulances by model name. Set `Config.AmbulanceModel` to the model name that you'd use to to spawn the vehicle.

If the add on ambulance has a lower capacity, be sure to change `Config.MaxPatientsPerTrip` to the appropriate number. If peds are standing around when you pull up, this is the likely cause.

Let me know if this doesn't work or if you have any other issues. Thanks!
