### ISSUE TITLE
Multiple EMS Cars

### ISSUE THREAD

**Issue by KaosBass** [propstg/ambulance-mission#17]
Hey,

Awesome work on the custom models, been trying to add multiple EMS cars to it though as I have 3-4 different EMS cars they use.

More a feature suggestion - Multiple Model Support

**Comment by propstg** [comment]
Hey, sorry for the delay. Good suggestion!

I merged a change to allow more than one model. You should be able to add lines to the Config.AmbulanceModels table to add your different EMS cars.

Let me know if you have any issues with the change. Thanks!
