### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by sflabrie** [propstg/ambulance-mission#22]
I install everything that you said and it's not work.

Can you help me for this.

thanks

**Comment by propstg** [comment]
Are there any errors in the log?

**Comment by propstg** [comment]
Or is there any more information that you can provide?

**Comment by sflabrie** [comment]
it's finally work , but I have one more question.
The 100$ they receive, it's the player receive the money. How can i do that the EMS_Society receive the money ?
Thanks

**Comment by propstg** [comment]
@sflabrie,

I've never used esx_society, so I'm not sure. Looking at the readme for that project, it looks like you might need to change the following event handler in this project's `src/server/main.lua` file from 

```
Wrapper.AddEventHandler('blargleambulance:finishLevel', function(levelFinished)
    ESX.GetPlayerFromId(source).addMoney(Config.Formulas.moneyPerLevel(levelFinished))
end)
```
to _something_ like this... (assuming `EMS_Society` is the name of the society)
```
Wrapper.AddEventHandler('blargleambulance:finishLevel', function(levelFinished)
    TriggerEvent('esx_society:depositMoney', 'EMS_Society', Config.Formulas.moneyPerLevel(levelFinished))
end)
```

**Comment by sflabrie** [comment]
Hi,

I will try, they said that the mission work but the Society not receive the money.

this is the error that i have :
SCRIPT ERROT: @esx_society/server/main.lua:92: attempt to index a nil value(local 'society'

This is the line 92 : if xPlayer.job.name ~= society.name then

This the line 86 to 107

RegisterServerEvent('esx_society:depositMoney')
AddEventHandler('esx_society:depositMoney', function(society, amount)
	local xPlayer = ESX.GetPlayerFromId(source)
	local society = GetSociety(society)
	amount = ESX.Math.Round(tonumber(amount))

	if xPlayer.job.name ~= society.name then
		print(('esx_society: %s attempted to call depositMoney!'):format(xPlayer.identifier))
		return
	end

	if amount > 0 and xPlayer.getMoney() >= amount then
		TriggerEvent('esx_addonaccount:getSharedAccount', society.account, function(account)
			xPlayer.removeMoney(amount)
			account.addMoney(amount)
		end)

		TriggerClientEvent('esx:showNotification', xPlayer.source, _U('have_deposited', ESX.Math.GroupDigits(amount)))
	else
		TriggerClientEvent('esx:showNotification', xPlayer.source, _U('invalid_amount'))
	end
end)

Let me know if you can do something, thanks

**Comment by propstg** [comment]
@sflabrie,

Hmm, if `society` is nil on that line, then `local society = GetSociety(society)` must be returning nil. Which I suspect means that 'EMS_Society' is the wrong name?

What script are you using that created the EMS society? Could probably find the right value there.

**Comment by sflabrie** [comment]
I used Esx_Society and esx_Ambulancejob
I changes EMS_society for "society_ambulance" it's what I have in my SQL.


This what i put in server/main.lua
Wrapper.AddEventHandler('blargleambulance:finishLevel', function(levelFinished)
    TriggerEvent('esx_society:depositMoney', 'society_ambulance', Config.Formulas.moneyPerLevel(levelFinished))
end)

and client/main.lua
Wrapper.TriggerServerEvent('esx_society:depositMoney', 'society_ambulance', Config.Formulas.moneyPerLevel(gameData.level))

**Comment by propstg** [comment]
@sflabrie,

Using the DB name does make sense. I'd suggest trying `'ambulance'` instead of `'society_ambulance'`, though. Reasoning below, in case it can help point you in the right direction if I'm wrong. 🙂 

---

in **esx_society**, `GetSociety` compares against the society's name, meaning the esx_society:depositMoney call should pass in the name.
```
function GetSociety(name)
	for i=1, #RegisteredSocieties, 1 do
		if RegisteredSocieties[i].name == name then
			return RegisteredSocieties[i]
...
```

---

**esx_ambulancejob** registers itself with this call: 
```
TriggerEvent('esx_society:registerSociety', 'ambulance', 'Ambulance', 'society_ambulance', 'society_ambulance', 'society_ambulance', {type = 'public'})
```

---

**esx_society's** handler for esx_society:registerSociety shows the first argument is the name, which looks like it should be 'ambulance' based on how esx_ambulancejob is calling it.
```
AddEventHandler('esx_society:registerSociety', function(name, label, account, datastore, inventory, data)
```

**Comment by sflabrie** [comment]
Thank you it's work perfectly.

I really appriciate your help and your script

**Comment by propstg** [comment]
Awesome, glad to hear that! Thanks for your patience. Let me know if you have any more issues.
