### ISSUE TITLE
Only for job ambulance

### ISSUE THREAD

**Issue by zelizz** [propstg/ambulance-mission#3]
Hi, nice script ! 

Any way to restrict it to ambulance job ? 
Each time I try to add
```
if PlayerData ~= nil and PlayerData.job == 'ambulance' then
xxxxxx
end
```
Game wont start, whereever I put it , any help 

Thx 

EDIT : OFC I have set the job ambulance to myself

**Comment by propstg** [comment]
Hey, thanks.

I just pushed a change to add an option to the config to restrict it to the ambulance job. If you pull the latest commit and change Config.LimitToAmbulanceJob to true, it should hopefully work how you're wanting it.

Please let me know if you have any issues with the change.

**Comment by zelizz** [comment]
Ye it works , nice job again ;) will pull french locales, may be usefull for some guys :)

**Comment by MoravianLion** [comment]
I wanted to say "thank you" as well, for EMS restriction :)
