### ISSUE TITLE
Only for EMS staff?

### ISSUE THREAD

**Issue by MoravianLion** [propstg/ambulance-mission#6]
Hi, I was trying to set this only for EMS employees, but can't get around playerdata to get it working. What am I doing wrong here, please?

Awesome script, btw.!

`
    playerData = {

    ped = nil,
    position = nil,
    vehicle = nil,
    isInAmbulance = false,
    isAmbulanceDriveable = false,
    isPlayerDead = false,
    job.name == ('ambulance'),
	}
`

**Comment by propstg** [comment]
Oh hey, glad you found the other issue addressing this. Thanks!
